import re
import difflib
from typing import List, Dict
from backend.core.models import UnusedDependencyResult
from backend.core.github_client import GitHubClient


class PRSubmitter:

    def __init__(self, github_client):
        # type: (GitHubClient) -> None
        self.github = github_client

    def build_modified_gradle(self, original_content, selections):
        # type: (str, List[UnusedDependencyResult]) -> str
        lines           = original_content.splitlines(keepends=True)
        lines_to_remove = set()
        lines_to_move   = {}

        for result in selections:
            ln = result.declaration.line_number - 1
            if result.is_test_only:
                old_line = lines[ln]
                new_line = re.sub(
                    r"^(\s*)(implementation|api|compileOnly)",
                    r"\1testImplementation",
                    old_line,
                )
                lines_to_move[ln] = new_line
            else:
                lines_to_remove.add(ln)

        new_lines = []
        for i, line in enumerate(lines):
            if i in lines_to_remove:
                continue
            elif i in lines_to_move:
                new_lines.append(lines_to_move[i])
            else:
                new_lines.append(line)

        return "".join(new_lines)

    def compute_diff(self, original, modified, file_path):
        # type: (str, str, str) -> str
        diff = difflib.unified_diff(
            original.splitlines(keepends=True),
            modified.splitlines(keepends=True),
            fromfile="a/{}".format(file_path),
            tofile="b/{}".format(file_path),
        )
        return "".join(diff)

    def submit_pr(self, selections_by_file, base_branch,
                  pr_branch, pr_title, pr_description):
        # type: (Dict[str, List[UnusedDependencyResult]], str, str, str, str) -> str
        if not selections_by_file:
            return ""

        head_sha = self.github.get_branch_sha(base_branch)
        self.github.create_branch(pr_branch, head_sha)

        committed  = []
        for gradle_path, selections in selections_by_file.items():
            original   = self.github.get_file_content(gradle_path, base_branch)
            modified   = self.build_modified_gradle(original, selections)
            file_sha   = self.github.get_file_sha(gradle_path, base_branch)
            removed    = [r for r in selections if r.is_unused]
            moved      = [r for r in selections if r.is_test_only]
            msg_parts  = []
            if removed:
                msg_parts.append("remove {} unused dep(s)".format(len(removed)))
            if moved:
                msg_parts.append("move {} to testImplementation".format(len(moved)))
            commit_msg = "chore(deps): {} in {}".format(
                ", ".join(msg_parts), gradle_path
            )
            self.github.commit_file(
                path=gradle_path, new_content=modified,
                branch=pr_branch, message=commit_msg,
                file_sha=file_sha,
            )
            committed.append((gradle_path, removed, moved))

        body_lines = [pr_description, "", "---", "### Changes", ""]
        for gradle_path, removed, moved in committed:
            body_lines.append("**`{}`**".format(gradle_path))
            for r in removed:
                body_lines.append("- Removed `{}` — {}".format(
                    r.declaration.gav, r.reason
                ))
            for r in moved:
                body_lines.append("- Moved `{}` to testImplementation — {}".format(
                    r.declaration.gav, r.reason
                ))
            body_lines.append("")
        body_lines.append("_Generated by dependency_refractor_")

        return self.github.create_pr(
            title=pr_title,
            body="\n".join(body_lines),
            head_branch=pr_branch,
            base_branch=base_branch,
        )